# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59fab12362379f5de4753f9b7a9d5b374230f2f88be99dc0ae22dd8c9eb212f56a93408d5a18da3e77a125f98dd369c3091b3ac29d54bd85f07d1ba49489a63b

test:
  secret_key_base: 60dfae3c445fab8b9a77c2a533c3604da992c8159a8fb5f9e1dc6f03cb3841b37d7c94da683039db4bc06befda9173ed315476fdb489a16ea88b3ed71fd883e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
